/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as EngineerRouteImport } from './routes/engineer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as OrdersRouteRouteImport } from './routes/orders/route'
import { Route as PasswordResetRouteImport } from './routes/password-reset'
import { Route as ProfileRouteRouteImport } from './routes/profile/route'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as CatalogIndexRouteImport } from './routes/catalog/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineerRoute = EngineerRouteImport.update({
  id: '/engineer',
  path: '/engineer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRouteRoute = OrdersRouteRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordResetRoute = PasswordResetRouteImport.update({
  id: '/password-reset',
  path: '/password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRouteRoute = ProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrdersRouteRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/orders': typeof OrdersRouteRouteWithChildren
  '/profile': typeof ProfileRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/engineer': typeof EngineerRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/password-reset': typeof PasswordResetRoute
  '/register': typeof RegisterRoute
  '/admin/': typeof AdminIndexRoute
  '/catalog/': typeof CatalogIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/engineer': typeof EngineerRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/password-reset': typeof PasswordResetRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AdminIndexRoute
  '/catalog': typeof CatalogIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/orders': typeof OrdersRouteRouteWithChildren
  '/profile': typeof ProfileRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/engineer': typeof EngineerRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/password-reset': typeof PasswordResetRoute
  '/register': typeof RegisterRoute
  '/admin/': typeof AdminIndexRoute
  '/catalog/': typeof CatalogIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/orders'
    | '/profile'
    | '/about'
    | '/engineer'
    | '/login'
    | '/manager'
    | '/password-reset'
    | '/register'
    | '/admin/'
    | '/catalog/'
    | '/orders/'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/engineer'
    | '/login'
    | '/manager'
    | '/password-reset'
    | '/register'
    | '/admin'
    | '/catalog'
    | '/orders'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/orders'
    | '/profile'
    | '/about'
    | '/engineer'
    | '/login'
    | '/manager'
    | '/password-reset'
    | '/register'
    | '/admin/'
    | '/catalog/'
    | '/orders/'
    | '/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  OrdersRouteRoute: typeof OrdersRouteRouteWithChildren
  ProfileRouteRoute: typeof ProfileRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  EngineerRoute: typeof EngineerRoute
  LoginRoute: typeof LoginRoute
  ManagerRoute: typeof ManagerRoute
  PasswordResetRoute: typeof PasswordResetRoute
  RegisterRoute: typeof RegisterRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineer': {
      id: '/engineer'
      path: '/engineer'
      fullPath: '/engineer'
      preLoaderRoute: typeof EngineerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-reset': {
      id: '/password-reset'
      path: '/password-reset'
      fullPath: '/password-reset'
      preLoaderRoute: typeof PasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof OrdersRouteRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface OrdersRouteRouteChildren {
  OrdersIndexRoute: typeof OrdersIndexRoute
}

const OrdersRouteRouteChildren: OrdersRouteRouteChildren = {
  OrdersIndexRoute: OrdersIndexRoute,
}

const OrdersRouteRouteWithChildren = OrdersRouteRoute._addFileChildren(
  OrdersRouteRouteChildren,
)

interface ProfileRouteRouteChildren {
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteRouteChildren: ProfileRouteRouteChildren = {
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteRouteWithChildren = ProfileRouteRoute._addFileChildren(
  ProfileRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  OrdersRouteRoute: OrdersRouteRouteWithChildren,
  ProfileRouteRoute: ProfileRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  EngineerRoute: EngineerRoute,
  LoginRoute: LoginRoute,
  ManagerRoute: ManagerRoute,
  PasswordResetRoute: PasswordResetRoute,
  RegisterRoute: RegisterRoute,
  CatalogIndexRoute: CatalogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
