/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as EngineerRouteRouteImport } from './routes/engineer/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as OrdersRouteRouteImport } from './routes/orders/route'
import { Route as PasswordResetRouteImport } from './routes/password-reset'
import { Route as ProfileRouteRouteImport } from './routes/profile/route'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RequestsRouteRouteImport } from './routes/requests/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as CartIndexRouteImport } from './routes/cart/index'
import { Route as CartSuccessRouteImport } from './routes/cart/success'
import { Route as CatalogIndexRouteImport } from './routes/catalog/index'
import { Route as CatalogCategoryIdRouteImport } from './routes/catalog/$categoryId'
import { Route as EngineerIndexRouteImport } from './routes/engineer/index'
import { Route as EngineerRequestIdRouteImport } from './routes/engineer/$requestId'
import { Route as NotificationsIndexRouteImport } from './routes/notifications/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders/$orderId'
import { Route as PagesSlugRouteImport } from './routes/pages/$slug'
import { Route as ProductSlugRouteImport } from './routes/product/$slug'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as ProfileEditRouteImport } from './routes/profile/edit'
import { Route as ProfileOrganizationRouteImport } from './routes/profile/organization'
import { Route as ProfileSecurityRouteImport } from './routes/profile/security'
import { Route as PromotionsIndexRouteImport } from './routes/promotions/index'
import { Route as PromotionsSlugRouteImport } from './routes/promotions/$slug'
import { Route as RequestsIndexRouteImport } from './routes/requests/index'
import { Route as RequestsRfqIdRouteImport } from './routes/requests/$rfqId'
import { Route as ServiceIndexRouteImport } from './routes/service/index'
import { Route as ServiceRequestsRouteRouteImport } from './routes/service/requests/route'
import { Route as ServiceSuccessRouteImport } from './routes/service/success'
import { Route as AdminBannersIndexRouteImport } from './routes/admin/banners/index'
import { Route as AdminCatalogIndexRouteImport } from './routes/admin/catalog/index'
import { Route as AdminCmsIndexRouteImport } from './routes/admin/cms/index'
import { Route as AdminCmsContactsRouteImport } from './routes/admin/cms/contacts'
import { Route as AdminCommerceIndexRouteImport } from './routes/admin/commerce/index'
import { Route as AdminCommerceRfqIdRouteImport } from './routes/admin/commerce/$rfqId'
import { Route as AdminReportsIndexRouteImport } from './routes/admin/reports/index'
import { Route as AdminServiceDeskIndexRouteImport } from './routes/admin/service-desk/index'
import { Route as AdminServiceDeskRequestIdRouteImport } from './routes/admin/service-desk/$requestId'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminUsersCustomerIdRouteImport } from './routes/admin/users/$customerId'
import { Route as ServiceRequestsIndexRouteImport } from './routes/service/requests/index'
import { Route as ServiceRequestsRequestIdRouteImport } from './routes/service/requests/$requestId'
import { Route as AdminCatalogCategoriesIndexRouteImport } from './routes/admin/catalog/categories/index'
import { Route as AdminCatalogCategoriesCategoryIdRouteImport } from './routes/admin/catalog/categories/$categoryId'
import { Route as AdminCatalogCategoriesNewRouteImport } from './routes/admin/catalog/categories/new'
import { Route as AdminCatalogProductsIndexRouteImport } from './routes/admin/catalog/products/index'
import { Route as AdminCatalogProductsProductIdRouteImport } from './routes/admin/catalog/products/$productId'
import { Route as AdminCatalogProductsNewRouteImport } from './routes/admin/catalog/products/new'
import { Route as AdminCmsPagesIndexRouteImport } from './routes/admin/cms/pages/index'
import { Route as AdminCmsPagesSlugRouteImport } from './routes/admin/cms/pages/$slug'
import { Route as AdminCmsPagesNewRouteImport } from './routes/admin/cms/pages/new'
import { Route as AdminCmsPromotionsIndexRouteImport } from './routes/admin/cms/promotions/index'
import { Route as AdminCmsPromotionsPromotionIdRouteImport } from './routes/admin/cms/promotions/$promotionId'
import { Route as AdminCmsPromotionsNewRouteImport } from './routes/admin/cms/promotions/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineerRouteRoute = EngineerRouteRouteImport.update({
  id: '/engineer',
  path: '/engineer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRouteRoute = OrdersRouteRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordResetRoute = PasswordResetRouteImport.update({
  id: '/password-reset',
  path: '/password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRouteRoute = ProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRouteRoute = RequestsRouteRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CartIndexRoute = CartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartSuccessRoute = CartSuccessRouteImport.update({
  id: '/cart/success',
  path: '/cart/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogCategoryIdRoute = CatalogCategoryIdRouteImport.update({
  id: '/catalog/$categoryId',
  path: '/catalog/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineerIndexRoute = EngineerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EngineerRouteRoute,
} as any)
const EngineerRequestIdRoute = EngineerRequestIdRouteImport.update({
  id: '/$requestId',
  path: '/$requestId',
  getParentRoute: () => EngineerRouteRoute,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrdersRouteRoute,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => OrdersRouteRoute,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProfileOrganizationRoute = ProfileOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProfileSecurityRoute = ProfileSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const PromotionsIndexRoute = PromotionsIndexRouteImport.update({
  id: '/promotions/',
  path: '/promotions/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsSlugRoute = PromotionsSlugRouteImport.update({
  id: '/promotions/$slug',
  path: '/promotions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RequestsRouteRoute,
} as any)
const RequestsRfqIdRoute = RequestsRfqIdRouteImport.update({
  id: '/$rfqId',
  path: '/$rfqId',
  getParentRoute: () => RequestsRouteRoute,
} as any)
const ServiceIndexRoute = ServiceIndexRouteImport.update({
  id: '/service/',
  path: '/service/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRequestsRouteRoute = ServiceRequestsRouteRouteImport.update({
  id: '/service/requests',
  path: '/service/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceSuccessRoute = ServiceSuccessRouteImport.update({
  id: '/service/success',
  path: '/service/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBannersIndexRoute = AdminBannersIndexRouteImport.update({
  id: '/banners/',
  path: '/banners/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCatalogIndexRoute = AdminCatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCmsIndexRoute = AdminCmsIndexRouteImport.update({
  id: '/cms/',
  path: '/cms/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCmsContactsRoute = AdminCmsContactsRouteImport.update({
  id: '/cms/contacts',
  path: '/cms/contacts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCommerceIndexRoute = AdminCommerceIndexRouteImport.update({
  id: '/commerce/',
  path: '/commerce/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCommerceRfqIdRoute = AdminCommerceRfqIdRouteImport.update({
  id: '/commerce/$rfqId',
  path: '/commerce/$rfqId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsIndexRoute = AdminReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminServiceDeskIndexRoute = AdminServiceDeskIndexRouteImport.update({
  id: '/service-desk/',
  path: '/service-desk/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminServiceDeskRequestIdRoute =
  AdminServiceDeskRequestIdRouteImport.update({
    id: '/service-desk/$requestId',
    path: '/service-desk/$requestId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersCustomerIdRoute = AdminUsersCustomerIdRouteImport.update({
  id: '/users/$customerId',
  path: '/users/$customerId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ServiceRequestsIndexRoute = ServiceRequestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServiceRequestsRouteRoute,
} as any)
const ServiceRequestsRequestIdRoute =
  ServiceRequestsRequestIdRouteImport.update({
    id: '/$requestId',
    path: '/$requestId',
    getParentRoute: () => ServiceRequestsRouteRoute,
  } as any)
const AdminCatalogCategoriesIndexRoute =
  AdminCatalogCategoriesIndexRouteImport.update({
    id: '/catalog/categories/',
    path: '/catalog/categories/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminCatalogCategoriesCategoryIdRoute =
  AdminCatalogCategoriesCategoryIdRouteImport.update({
    id: '/catalog/categories/$categoryId',
    path: '/catalog/categories/$categoryId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminCatalogCategoriesNewRoute =
  AdminCatalogCategoriesNewRouteImport.update({
    id: '/catalog/categories/new',
    path: '/catalog/categories/new',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminCatalogProductsIndexRoute =
  AdminCatalogProductsIndexRouteImport.update({
    id: '/catalog/products/',
    path: '/catalog/products/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminCatalogProductsProductIdRoute =
  AdminCatalogProductsProductIdRouteImport.update({
    id: '/catalog/products/$productId',
    path: '/catalog/products/$productId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminCatalogProductsNewRoute = AdminCatalogProductsNewRouteImport.update({
  id: '/catalog/products/new',
  path: '/catalog/products/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCmsPagesIndexRoute = AdminCmsPagesIndexRouteImport.update({
  id: '/cms/pages/',
  path: '/cms/pages/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCmsPagesSlugRoute = AdminCmsPagesSlugRouteImport.update({
  id: '/cms/pages/$slug',
  path: '/cms/pages/$slug',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCmsPagesNewRoute = AdminCmsPagesNewRouteImport.update({
  id: '/cms/pages/new',
  path: '/cms/pages/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCmsPromotionsIndexRoute = AdminCmsPromotionsIndexRouteImport.update({
  id: '/cms/promotions/',
  path: '/cms/promotions/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCmsPromotionsPromotionIdRoute =
  AdminCmsPromotionsPromotionIdRouteImport.update({
    id: '/cms/promotions/$promotionId',
    path: '/cms/promotions/$promotionId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminCmsPromotionsNewRoute = AdminCmsPromotionsNewRouteImport.update({
  id: '/cms/promotions/new',
  path: '/cms/promotions/new',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/engineer': typeof EngineerRouteRouteWithChildren
  '/orders': typeof OrdersRouteRouteWithChildren
  '/profile': typeof ProfileRouteRouteWithChildren
  '/requests': typeof RequestsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contacts': typeof ContactsRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/password-reset': typeof PasswordResetRoute
  '/register': typeof RegisterRoute
  '/service/requests': typeof ServiceRequestsRouteRouteWithChildren
  '/cart/success': typeof CartSuccessRoute
  '/catalog/$categoryId': typeof CatalogCategoryIdRoute
  '/engineer/$requestId': typeof EngineerRequestIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/organization': typeof ProfileOrganizationRoute
  '/profile/security': typeof ProfileSecurityRoute
  '/promotions/$slug': typeof PromotionsSlugRoute
  '/requests/$rfqId': typeof RequestsRfqIdRoute
  '/service/success': typeof ServiceSuccessRoute
  '/admin/': typeof AdminIndexRoute
  '/cart/': typeof CartIndexRoute
  '/catalog/': typeof CatalogIndexRoute
  '/engineer/': typeof EngineerIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/promotions/': typeof PromotionsIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/service/': typeof ServiceIndexRoute
  '/admin/cms/contacts': typeof AdminCmsContactsRoute
  '/admin/commerce/$rfqId': typeof AdminCommerceRfqIdRoute
  '/admin/service-desk/$requestId': typeof AdminServiceDeskRequestIdRoute
  '/admin/users/$customerId': typeof AdminUsersCustomerIdRoute
  '/service/requests/$requestId': typeof ServiceRequestsRequestIdRoute
  '/admin/banners/': typeof AdminBannersIndexRoute
  '/admin/catalog/': typeof AdminCatalogIndexRoute
  '/admin/cms/': typeof AdminCmsIndexRoute
  '/admin/commerce/': typeof AdminCommerceIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/admin/service-desk/': typeof AdminServiceDeskIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/service/requests/': typeof ServiceRequestsIndexRoute
  '/admin/catalog/categories/$categoryId': typeof AdminCatalogCategoriesCategoryIdRoute
  '/admin/catalog/categories/new': typeof AdminCatalogCategoriesNewRoute
  '/admin/catalog/products/$productId': typeof AdminCatalogProductsProductIdRoute
  '/admin/catalog/products/new': typeof AdminCatalogProductsNewRoute
  '/admin/cms/pages/$slug': typeof AdminCmsPagesSlugRoute
  '/admin/cms/pages/new': typeof AdminCmsPagesNewRoute
  '/admin/cms/promotions/$promotionId': typeof AdminCmsPromotionsPromotionIdRoute
  '/admin/cms/promotions/new': typeof AdminCmsPromotionsNewRoute
  '/admin/catalog/categories/': typeof AdminCatalogCategoriesIndexRoute
  '/admin/catalog/products/': typeof AdminCatalogProductsIndexRoute
  '/admin/cms/pages/': typeof AdminCmsPagesIndexRoute
  '/admin/cms/promotions/': typeof AdminCmsPromotionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contacts': typeof ContactsRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/password-reset': typeof PasswordResetRoute
  '/register': typeof RegisterRoute
  '/cart/success': typeof CartSuccessRoute
  '/catalog/$categoryId': typeof CatalogCategoryIdRoute
  '/engineer/$requestId': typeof EngineerRequestIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/organization': typeof ProfileOrganizationRoute
  '/profile/security': typeof ProfileSecurityRoute
  '/promotions/$slug': typeof PromotionsSlugRoute
  '/requests/$rfqId': typeof RequestsRfqIdRoute
  '/service/success': typeof ServiceSuccessRoute
  '/admin': typeof AdminIndexRoute
  '/cart': typeof CartIndexRoute
  '/catalog': typeof CatalogIndexRoute
  '/engineer': typeof EngineerIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/promotions': typeof PromotionsIndexRoute
  '/requests': typeof RequestsIndexRoute
  '/service': typeof ServiceIndexRoute
  '/admin/cms/contacts': typeof AdminCmsContactsRoute
  '/admin/commerce/$rfqId': typeof AdminCommerceRfqIdRoute
  '/admin/service-desk/$requestId': typeof AdminServiceDeskRequestIdRoute
  '/admin/users/$customerId': typeof AdminUsersCustomerIdRoute
  '/service/requests/$requestId': typeof ServiceRequestsRequestIdRoute
  '/admin/banners': typeof AdminBannersIndexRoute
  '/admin/catalog': typeof AdminCatalogIndexRoute
  '/admin/cms': typeof AdminCmsIndexRoute
  '/admin/commerce': typeof AdminCommerceIndexRoute
  '/admin/reports': typeof AdminReportsIndexRoute
  '/admin/service-desk': typeof AdminServiceDeskIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/service/requests': typeof ServiceRequestsIndexRoute
  '/admin/catalog/categories/$categoryId': typeof AdminCatalogCategoriesCategoryIdRoute
  '/admin/catalog/categories/new': typeof AdminCatalogCategoriesNewRoute
  '/admin/catalog/products/$productId': typeof AdminCatalogProductsProductIdRoute
  '/admin/catalog/products/new': typeof AdminCatalogProductsNewRoute
  '/admin/cms/pages/$slug': typeof AdminCmsPagesSlugRoute
  '/admin/cms/pages/new': typeof AdminCmsPagesNewRoute
  '/admin/cms/promotions/$promotionId': typeof AdminCmsPromotionsPromotionIdRoute
  '/admin/cms/promotions/new': typeof AdminCmsPromotionsNewRoute
  '/admin/catalog/categories': typeof AdminCatalogCategoriesIndexRoute
  '/admin/catalog/products': typeof AdminCatalogProductsIndexRoute
  '/admin/cms/pages': typeof AdminCmsPagesIndexRoute
  '/admin/cms/promotions': typeof AdminCmsPromotionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/engineer': typeof EngineerRouteRouteWithChildren
  '/orders': typeof OrdersRouteRouteWithChildren
  '/profile': typeof ProfileRouteRouteWithChildren
  '/requests': typeof RequestsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contacts': typeof ContactsRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/password-reset': typeof PasswordResetRoute
  '/register': typeof RegisterRoute
  '/service/requests': typeof ServiceRequestsRouteRouteWithChildren
  '/cart/success': typeof CartSuccessRoute
  '/catalog/$categoryId': typeof CatalogCategoryIdRoute
  '/engineer/$requestId': typeof EngineerRequestIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/organization': typeof ProfileOrganizationRoute
  '/profile/security': typeof ProfileSecurityRoute
  '/promotions/$slug': typeof PromotionsSlugRoute
  '/requests/$rfqId': typeof RequestsRfqIdRoute
  '/service/success': typeof ServiceSuccessRoute
  '/admin/': typeof AdminIndexRoute
  '/cart/': typeof CartIndexRoute
  '/catalog/': typeof CatalogIndexRoute
  '/engineer/': typeof EngineerIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/promotions/': typeof PromotionsIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/service/': typeof ServiceIndexRoute
  '/admin/cms/contacts': typeof AdminCmsContactsRoute
  '/admin/commerce/$rfqId': typeof AdminCommerceRfqIdRoute
  '/admin/service-desk/$requestId': typeof AdminServiceDeskRequestIdRoute
  '/admin/users/$customerId': typeof AdminUsersCustomerIdRoute
  '/service/requests/$requestId': typeof ServiceRequestsRequestIdRoute
  '/admin/banners/': typeof AdminBannersIndexRoute
  '/admin/catalog/': typeof AdminCatalogIndexRoute
  '/admin/cms/': typeof AdminCmsIndexRoute
  '/admin/commerce/': typeof AdminCommerceIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/admin/service-desk/': typeof AdminServiceDeskIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/service/requests/': typeof ServiceRequestsIndexRoute
  '/admin/catalog/categories/$categoryId': typeof AdminCatalogCategoriesCategoryIdRoute
  '/admin/catalog/categories/new': typeof AdminCatalogCategoriesNewRoute
  '/admin/catalog/products/$productId': typeof AdminCatalogProductsProductIdRoute
  '/admin/catalog/products/new': typeof AdminCatalogProductsNewRoute
  '/admin/cms/pages/$slug': typeof AdminCmsPagesSlugRoute
  '/admin/cms/pages/new': typeof AdminCmsPagesNewRoute
  '/admin/cms/promotions/$promotionId': typeof AdminCmsPromotionsPromotionIdRoute
  '/admin/cms/promotions/new': typeof AdminCmsPromotionsNewRoute
  '/admin/catalog/categories/': typeof AdminCatalogCategoriesIndexRoute
  '/admin/catalog/products/': typeof AdminCatalogProductsIndexRoute
  '/admin/cms/pages/': typeof AdminCmsPagesIndexRoute
  '/admin/cms/promotions/': typeof AdminCmsPromotionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/engineer'
    | '/orders'
    | '/profile'
    | '/requests'
    | '/about'
    | '/contacts'
    | '/login'
    | '/manager'
    | '/password-reset'
    | '/register'
    | '/service/requests'
    | '/cart/success'
    | '/catalog/$categoryId'
    | '/engineer/$requestId'
    | '/orders/$orderId'
    | '/pages/$slug'
    | '/product/$slug'
    | '/profile/edit'
    | '/profile/organization'
    | '/profile/security'
    | '/promotions/$slug'
    | '/requests/$rfqId'
    | '/service/success'
    | '/admin/'
    | '/cart/'
    | '/catalog/'
    | '/engineer/'
    | '/notifications/'
    | '/orders/'
    | '/profile/'
    | '/promotions/'
    | '/requests/'
    | '/service/'
    | '/admin/cms/contacts'
    | '/admin/commerce/$rfqId'
    | '/admin/service-desk/$requestId'
    | '/admin/users/$customerId'
    | '/service/requests/$requestId'
    | '/admin/banners/'
    | '/admin/catalog/'
    | '/admin/cms/'
    | '/admin/commerce/'
    | '/admin/reports/'
    | '/admin/service-desk/'
    | '/admin/users/'
    | '/service/requests/'
    | '/admin/catalog/categories/$categoryId'
    | '/admin/catalog/categories/new'
    | '/admin/catalog/products/$productId'
    | '/admin/catalog/products/new'
    | '/admin/cms/pages/$slug'
    | '/admin/cms/pages/new'
    | '/admin/cms/promotions/$promotionId'
    | '/admin/cms/promotions/new'
    | '/admin/catalog/categories/'
    | '/admin/catalog/products/'
    | '/admin/cms/pages/'
    | '/admin/cms/promotions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contacts'
    | '/login'
    | '/manager'
    | '/password-reset'
    | '/register'
    | '/cart/success'
    | '/catalog/$categoryId'
    | '/engineer/$requestId'
    | '/orders/$orderId'
    | '/pages/$slug'
    | '/product/$slug'
    | '/profile/edit'
    | '/profile/organization'
    | '/profile/security'
    | '/promotions/$slug'
    | '/requests/$rfqId'
    | '/service/success'
    | '/admin'
    | '/cart'
    | '/catalog'
    | '/engineer'
    | '/notifications'
    | '/orders'
    | '/profile'
    | '/promotions'
    | '/requests'
    | '/service'
    | '/admin/cms/contacts'
    | '/admin/commerce/$rfqId'
    | '/admin/service-desk/$requestId'
    | '/admin/users/$customerId'
    | '/service/requests/$requestId'
    | '/admin/banners'
    | '/admin/catalog'
    | '/admin/cms'
    | '/admin/commerce'
    | '/admin/reports'
    | '/admin/service-desk'
    | '/admin/users'
    | '/service/requests'
    | '/admin/catalog/categories/$categoryId'
    | '/admin/catalog/categories/new'
    | '/admin/catalog/products/$productId'
    | '/admin/catalog/products/new'
    | '/admin/cms/pages/$slug'
    | '/admin/cms/pages/new'
    | '/admin/cms/promotions/$promotionId'
    | '/admin/cms/promotions/new'
    | '/admin/catalog/categories'
    | '/admin/catalog/products'
    | '/admin/cms/pages'
    | '/admin/cms/promotions'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/engineer'
    | '/orders'
    | '/profile'
    | '/requests'
    | '/about'
    | '/contacts'
    | '/login'
    | '/manager'
    | '/password-reset'
    | '/register'
    | '/service/requests'
    | '/cart/success'
    | '/catalog/$categoryId'
    | '/engineer/$requestId'
    | '/orders/$orderId'
    | '/pages/$slug'
    | '/product/$slug'
    | '/profile/edit'
    | '/profile/organization'
    | '/profile/security'
    | '/promotions/$slug'
    | '/requests/$rfqId'
    | '/service/success'
    | '/admin/'
    | '/cart/'
    | '/catalog/'
    | '/engineer/'
    | '/notifications/'
    | '/orders/'
    | '/profile/'
    | '/promotions/'
    | '/requests/'
    | '/service/'
    | '/admin/cms/contacts'
    | '/admin/commerce/$rfqId'
    | '/admin/service-desk/$requestId'
    | '/admin/users/$customerId'
    | '/service/requests/$requestId'
    | '/admin/banners/'
    | '/admin/catalog/'
    | '/admin/cms/'
    | '/admin/commerce/'
    | '/admin/reports/'
    | '/admin/service-desk/'
    | '/admin/users/'
    | '/service/requests/'
    | '/admin/catalog/categories/$categoryId'
    | '/admin/catalog/categories/new'
    | '/admin/catalog/products/$productId'
    | '/admin/catalog/products/new'
    | '/admin/cms/pages/$slug'
    | '/admin/cms/pages/new'
    | '/admin/cms/promotions/$promotionId'
    | '/admin/cms/promotions/new'
    | '/admin/catalog/categories/'
    | '/admin/catalog/products/'
    | '/admin/cms/pages/'
    | '/admin/cms/promotions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  EngineerRouteRoute: typeof EngineerRouteRouteWithChildren
  OrdersRouteRoute: typeof OrdersRouteRouteWithChildren
  ProfileRouteRoute: typeof ProfileRouteRouteWithChildren
  RequestsRouteRoute: typeof RequestsRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactsRoute: typeof ContactsRoute
  LoginRoute: typeof LoginRoute
  ManagerRoute: typeof ManagerRoute
  PasswordResetRoute: typeof PasswordResetRoute
  RegisterRoute: typeof RegisterRoute
  ServiceRequestsRouteRoute: typeof ServiceRequestsRouteRouteWithChildren
  CartSuccessRoute: typeof CartSuccessRoute
  CatalogCategoryIdRoute: typeof CatalogCategoryIdRoute
  PagesSlugRoute: typeof PagesSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  PromotionsSlugRoute: typeof PromotionsSlugRoute
  ServiceSuccessRoute: typeof ServiceSuccessRoute
  CartIndexRoute: typeof CartIndexRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
  PromotionsIndexRoute: typeof PromotionsIndexRoute
  ServiceIndexRoute: typeof ServiceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineer': {
      id: '/engineer'
      path: '/engineer'
      fullPath: '/engineer'
      preLoaderRoute: typeof EngineerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-reset': {
      id: '/password-reset'
      path: '/password-reset'
      fullPath: '/password-reset'
      preLoaderRoute: typeof PasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/cart/': {
      id: '/cart/'
      path: '/cart'
      fullPath: '/cart/'
      preLoaderRoute: typeof CartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/success': {
      id: '/cart/success'
      path: '/cart/success'
      fullPath: '/cart/success'
      preLoaderRoute: typeof CartSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/$categoryId': {
      id: '/catalog/$categoryId'
      path: '/catalog/$categoryId'
      fullPath: '/catalog/$categoryId'
      preLoaderRoute: typeof CatalogCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineer/': {
      id: '/engineer/'
      path: '/'
      fullPath: '/engineer/'
      preLoaderRoute: typeof EngineerIndexRouteImport
      parentRoute: typeof EngineerRouteRoute
    }
    '/engineer/$requestId': {
      id: '/engineer/$requestId'
      path: '/$requestId'
      fullPath: '/engineer/$requestId'
      preLoaderRoute: typeof EngineerRequestIdRouteImport
      parentRoute: typeof EngineerRouteRoute
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof OrdersRouteRoute
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof OrdersRouteRoute
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/profile/organization': {
      id: '/profile/organization'
      path: '/organization'
      fullPath: '/profile/organization'
      preLoaderRoute: typeof ProfileOrganizationRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/profile/security': {
      id: '/profile/security'
      path: '/security'
      fullPath: '/profile/security'
      preLoaderRoute: typeof ProfileSecurityRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/promotions/': {
      id: '/promotions/'
      path: '/promotions'
      fullPath: '/promotions/'
      preLoaderRoute: typeof PromotionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions/$slug': {
      id: '/promotions/$slug'
      path: '/promotions/$slug'
      fullPath: '/promotions/$slug'
      preLoaderRoute: typeof PromotionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/': {
      id: '/requests/'
      path: '/'
      fullPath: '/requests/'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof RequestsRouteRoute
    }
    '/requests/$rfqId': {
      id: '/requests/$rfqId'
      path: '/$rfqId'
      fullPath: '/requests/$rfqId'
      preLoaderRoute: typeof RequestsRfqIdRouteImport
      parentRoute: typeof RequestsRouteRoute
    }
    '/service/': {
      id: '/service/'
      path: '/service'
      fullPath: '/service/'
      preLoaderRoute: typeof ServiceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/requests': {
      id: '/service/requests'
      path: '/service/requests'
      fullPath: '/service/requests'
      preLoaderRoute: typeof ServiceRequestsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/success': {
      id: '/service/success'
      path: '/service/success'
      fullPath: '/service/success'
      preLoaderRoute: typeof ServiceSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/banners/': {
      id: '/admin/banners/'
      path: '/banners'
      fullPath: '/admin/banners/'
      preLoaderRoute: typeof AdminBannersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/catalog/': {
      id: '/admin/catalog/'
      path: '/catalog'
      fullPath: '/admin/catalog/'
      preLoaderRoute: typeof AdminCatalogIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cms/': {
      id: '/admin/cms/'
      path: '/cms'
      fullPath: '/admin/cms/'
      preLoaderRoute: typeof AdminCmsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cms/contacts': {
      id: '/admin/cms/contacts'
      path: '/cms/contacts'
      fullPath: '/admin/cms/contacts'
      preLoaderRoute: typeof AdminCmsContactsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/commerce/': {
      id: '/admin/commerce/'
      path: '/commerce'
      fullPath: '/admin/commerce/'
      preLoaderRoute: typeof AdminCommerceIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/commerce/$rfqId': {
      id: '/admin/commerce/$rfqId'
      path: '/commerce/$rfqId'
      fullPath: '/admin/commerce/$rfqId'
      preLoaderRoute: typeof AdminCommerceRfqIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports/': {
      id: '/admin/reports/'
      path: '/reports'
      fullPath: '/admin/reports/'
      preLoaderRoute: typeof AdminReportsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/service-desk/': {
      id: '/admin/service-desk/'
      path: '/service-desk'
      fullPath: '/admin/service-desk/'
      preLoaderRoute: typeof AdminServiceDeskIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/service-desk/$requestId': {
      id: '/admin/service-desk/$requestId'
      path: '/service-desk/$requestId'
      fullPath: '/admin/service-desk/$requestId'
      preLoaderRoute: typeof AdminServiceDeskRequestIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/$customerId': {
      id: '/admin/users/$customerId'
      path: '/users/$customerId'
      fullPath: '/admin/users/$customerId'
      preLoaderRoute: typeof AdminUsersCustomerIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/service/requests/': {
      id: '/service/requests/'
      path: '/'
      fullPath: '/service/requests/'
      preLoaderRoute: typeof ServiceRequestsIndexRouteImport
      parentRoute: typeof ServiceRequestsRouteRoute
    }
    '/service/requests/$requestId': {
      id: '/service/requests/$requestId'
      path: '/$requestId'
      fullPath: '/service/requests/$requestId'
      preLoaderRoute: typeof ServiceRequestsRequestIdRouteImport
      parentRoute: typeof ServiceRequestsRouteRoute
    }
    '/admin/catalog/categories/': {
      id: '/admin/catalog/categories/'
      path: '/catalog/categories'
      fullPath: '/admin/catalog/categories/'
      preLoaderRoute: typeof AdminCatalogCategoriesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/catalog/categories/$categoryId': {
      id: '/admin/catalog/categories/$categoryId'
      path: '/catalog/categories/$categoryId'
      fullPath: '/admin/catalog/categories/$categoryId'
      preLoaderRoute: typeof AdminCatalogCategoriesCategoryIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/catalog/categories/new': {
      id: '/admin/catalog/categories/new'
      path: '/catalog/categories/new'
      fullPath: '/admin/catalog/categories/new'
      preLoaderRoute: typeof AdminCatalogCategoriesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/catalog/products/': {
      id: '/admin/catalog/products/'
      path: '/catalog/products'
      fullPath: '/admin/catalog/products/'
      preLoaderRoute: typeof AdminCatalogProductsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/catalog/products/$productId': {
      id: '/admin/catalog/products/$productId'
      path: '/catalog/products/$productId'
      fullPath: '/admin/catalog/products/$productId'
      preLoaderRoute: typeof AdminCatalogProductsProductIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/catalog/products/new': {
      id: '/admin/catalog/products/new'
      path: '/catalog/products/new'
      fullPath: '/admin/catalog/products/new'
      preLoaderRoute: typeof AdminCatalogProductsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cms/pages/': {
      id: '/admin/cms/pages/'
      path: '/cms/pages'
      fullPath: '/admin/cms/pages/'
      preLoaderRoute: typeof AdminCmsPagesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cms/pages/$slug': {
      id: '/admin/cms/pages/$slug'
      path: '/cms/pages/$slug'
      fullPath: '/admin/cms/pages/$slug'
      preLoaderRoute: typeof AdminCmsPagesSlugRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cms/pages/new': {
      id: '/admin/cms/pages/new'
      path: '/cms/pages/new'
      fullPath: '/admin/cms/pages/new'
      preLoaderRoute: typeof AdminCmsPagesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cms/promotions/': {
      id: '/admin/cms/promotions/'
      path: '/cms/promotions'
      fullPath: '/admin/cms/promotions/'
      preLoaderRoute: typeof AdminCmsPromotionsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cms/promotions/$promotionId': {
      id: '/admin/cms/promotions/$promotionId'
      path: '/cms/promotions/$promotionId'
      fullPath: '/admin/cms/promotions/$promotionId'
      preLoaderRoute: typeof AdminCmsPromotionsPromotionIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cms/promotions/new': {
      id: '/admin/cms/promotions/new'
      path: '/cms/promotions/new'
      fullPath: '/admin/cms/promotions/new'
      preLoaderRoute: typeof AdminCmsPromotionsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCmsContactsRoute: typeof AdminCmsContactsRoute
  AdminCommerceRfqIdRoute: typeof AdminCommerceRfqIdRoute
  AdminServiceDeskRequestIdRoute: typeof AdminServiceDeskRequestIdRoute
  AdminUsersCustomerIdRoute: typeof AdminUsersCustomerIdRoute
  AdminBannersIndexRoute: typeof AdminBannersIndexRoute
  AdminCatalogIndexRoute: typeof AdminCatalogIndexRoute
  AdminCmsIndexRoute: typeof AdminCmsIndexRoute
  AdminCommerceIndexRoute: typeof AdminCommerceIndexRoute
  AdminReportsIndexRoute: typeof AdminReportsIndexRoute
  AdminServiceDeskIndexRoute: typeof AdminServiceDeskIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminCatalogCategoriesCategoryIdRoute: typeof AdminCatalogCategoriesCategoryIdRoute
  AdminCatalogCategoriesNewRoute: typeof AdminCatalogCategoriesNewRoute
  AdminCatalogProductsProductIdRoute: typeof AdminCatalogProductsProductIdRoute
  AdminCatalogProductsNewRoute: typeof AdminCatalogProductsNewRoute
  AdminCmsPagesSlugRoute: typeof AdminCmsPagesSlugRoute
  AdminCmsPagesNewRoute: typeof AdminCmsPagesNewRoute
  AdminCmsPromotionsPromotionIdRoute: typeof AdminCmsPromotionsPromotionIdRoute
  AdminCmsPromotionsNewRoute: typeof AdminCmsPromotionsNewRoute
  AdminCatalogCategoriesIndexRoute: typeof AdminCatalogCategoriesIndexRoute
  AdminCatalogProductsIndexRoute: typeof AdminCatalogProductsIndexRoute
  AdminCmsPagesIndexRoute: typeof AdminCmsPagesIndexRoute
  AdminCmsPromotionsIndexRoute: typeof AdminCmsPromotionsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminCmsContactsRoute: AdminCmsContactsRoute,
  AdminCommerceRfqIdRoute: AdminCommerceRfqIdRoute,
  AdminServiceDeskRequestIdRoute: AdminServiceDeskRequestIdRoute,
  AdminUsersCustomerIdRoute: AdminUsersCustomerIdRoute,
  AdminBannersIndexRoute: AdminBannersIndexRoute,
  AdminCatalogIndexRoute: AdminCatalogIndexRoute,
  AdminCmsIndexRoute: AdminCmsIndexRoute,
  AdminCommerceIndexRoute: AdminCommerceIndexRoute,
  AdminReportsIndexRoute: AdminReportsIndexRoute,
  AdminServiceDeskIndexRoute: AdminServiceDeskIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminCatalogCategoriesCategoryIdRoute: AdminCatalogCategoriesCategoryIdRoute,
  AdminCatalogCategoriesNewRoute: AdminCatalogCategoriesNewRoute,
  AdminCatalogProductsProductIdRoute: AdminCatalogProductsProductIdRoute,
  AdminCatalogProductsNewRoute: AdminCatalogProductsNewRoute,
  AdminCmsPagesSlugRoute: AdminCmsPagesSlugRoute,
  AdminCmsPagesNewRoute: AdminCmsPagesNewRoute,
  AdminCmsPromotionsPromotionIdRoute: AdminCmsPromotionsPromotionIdRoute,
  AdminCmsPromotionsNewRoute: AdminCmsPromotionsNewRoute,
  AdminCatalogCategoriesIndexRoute: AdminCatalogCategoriesIndexRoute,
  AdminCatalogProductsIndexRoute: AdminCatalogProductsIndexRoute,
  AdminCmsPagesIndexRoute: AdminCmsPagesIndexRoute,
  AdminCmsPromotionsIndexRoute: AdminCmsPromotionsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface EngineerRouteRouteChildren {
  EngineerRequestIdRoute: typeof EngineerRequestIdRoute
  EngineerIndexRoute: typeof EngineerIndexRoute
}

const EngineerRouteRouteChildren: EngineerRouteRouteChildren = {
  EngineerRequestIdRoute: EngineerRequestIdRoute,
  EngineerIndexRoute: EngineerIndexRoute,
}

const EngineerRouteRouteWithChildren = EngineerRouteRoute._addFileChildren(
  EngineerRouteRouteChildren,
)

interface OrdersRouteRouteChildren {
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

const OrdersRouteRouteChildren: OrdersRouteRouteChildren = {
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}

const OrdersRouteRouteWithChildren = OrdersRouteRoute._addFileChildren(
  OrdersRouteRouteChildren,
)

interface ProfileRouteRouteChildren {
  ProfileEditRoute: typeof ProfileEditRoute
  ProfileOrganizationRoute: typeof ProfileOrganizationRoute
  ProfileSecurityRoute: typeof ProfileSecurityRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteRouteChildren: ProfileRouteRouteChildren = {
  ProfileEditRoute: ProfileEditRoute,
  ProfileOrganizationRoute: ProfileOrganizationRoute,
  ProfileSecurityRoute: ProfileSecurityRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteRouteWithChildren = ProfileRouteRoute._addFileChildren(
  ProfileRouteRouteChildren,
)

interface RequestsRouteRouteChildren {
  RequestsRfqIdRoute: typeof RequestsRfqIdRoute
  RequestsIndexRoute: typeof RequestsIndexRoute
}

const RequestsRouteRouteChildren: RequestsRouteRouteChildren = {
  RequestsRfqIdRoute: RequestsRfqIdRoute,
  RequestsIndexRoute: RequestsIndexRoute,
}

const RequestsRouteRouteWithChildren = RequestsRouteRoute._addFileChildren(
  RequestsRouteRouteChildren,
)

interface ServiceRequestsRouteRouteChildren {
  ServiceRequestsRequestIdRoute: typeof ServiceRequestsRequestIdRoute
  ServiceRequestsIndexRoute: typeof ServiceRequestsIndexRoute
}

const ServiceRequestsRouteRouteChildren: ServiceRequestsRouteRouteChildren = {
  ServiceRequestsRequestIdRoute: ServiceRequestsRequestIdRoute,
  ServiceRequestsIndexRoute: ServiceRequestsIndexRoute,
}

const ServiceRequestsRouteRouteWithChildren =
  ServiceRequestsRouteRoute._addFileChildren(ServiceRequestsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  EngineerRouteRoute: EngineerRouteRouteWithChildren,
  OrdersRouteRoute: OrdersRouteRouteWithChildren,
  ProfileRouteRoute: ProfileRouteRouteWithChildren,
  RequestsRouteRoute: RequestsRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactsRoute: ContactsRoute,
  LoginRoute: LoginRoute,
  ManagerRoute: ManagerRoute,
  PasswordResetRoute: PasswordResetRoute,
  RegisterRoute: RegisterRoute,
  ServiceRequestsRouteRoute: ServiceRequestsRouteRouteWithChildren,
  CartSuccessRoute: CartSuccessRoute,
  CatalogCategoryIdRoute: CatalogCategoryIdRoute,
  PagesSlugRoute: PagesSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  PromotionsSlugRoute: PromotionsSlugRoute,
  ServiceSuccessRoute: ServiceSuccessRoute,
  CartIndexRoute: CartIndexRoute,
  CatalogIndexRoute: CatalogIndexRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
  PromotionsIndexRoute: PromotionsIndexRoute,
  ServiceIndexRoute: ServiceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
